### ISSUE TITLE
when i run it in repl.it it give a error

### ISSUE THREAD

**Issue by Arnob17** [TheGamer456YT/Economy-Bot#2]
Error: Cannot find module 'dotenv'
Require stack:
- /home/runner/Economy-Bot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/Economy-Bot/index.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/Economy-Bot/index.js' ]
}

**Comment by AllMesi** [comment]
type "npm i" in the console then see if it works
